import { useState } from 'react';
import { jsPDF } from 'jspdf';
import { Button } from './ui/Button';
import { FileText, Download, Sparkles, FileCheck } from 'lucide-react';
import { Card } from './ui/Card';
import { motion } from 'framer-motion';

export function ResumeBuilder({ roadmap, analysis, studentProfile }) {
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedSuccess, setGeneratedSuccess] = useState(false);

    const generateProfessionalResume = () => {
        setIsGenerating(true);
        setGeneratedSuccess(false);

        // Create PDF with better styling
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const margin = 20;
        const contentWidth = pageWidth - (margin * 2);
        let yPos = 20;

        // Colors
        const primaryColor = [59, 130, 246]; // Blue
        const textDark = [30, 41, 59]; // Slate-800
        const textMuted = [100, 116, 139]; // Slate-500

        // Helper for drawing horizontal lines
        const drawLine = (y, color = [226, 232, 240]) => {
            doc.setDrawColor(...color);
            doc.line(margin, y, pageWidth - margin, y);
        };

        // ============ HEADER SECTION ============
        // Blue header bar
        doc.setFillColor(...primaryColor);
        doc.rect(0, 0, pageWidth, 35, 'F');

        // Name
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(28);
        doc.setFont('helvetica', 'bold');
        const name = studentProfile?.name || 'Career Professional';
        doc.text(name, pageWidth / 2, 18, { align: 'center' });

        // Contact info
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        const contactInfo = [
            studentProfile?.email || 'email@example.com',
            studentProfile?.location || 'India',
            'Career Roadmap Generated by OPEC'
        ].join('  |  ');
        doc.text(contactInfo, pageWidth / 2, 28, { align: 'center' });

        yPos = 45;

        // ============ PROFESSIONAL SUMMARY ============
        doc.setTextColor(...primaryColor);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('PROFESSIONAL SUMMARY', margin, yPos);
        yPos += 3;
        drawLine(yPos, primaryColor);
        yPos += 8;

        doc.setTextColor(...textDark);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');

        // Get summary from analysis or generate one
        const summary = analysis?.counselor_view ||
            `Motivated ${studentProfile?.stream_or_branch || 'professional'} with a clear vision for career growth. ` +
            `Passionate about ${studentProfile?.interests?.slice(0, 2).join(' and ') || 'continuous learning'} ` +
            `with goals focused on ${studentProfile?.goals?.slice(0, 2).join(' and ') || 'professional development'}.`;

        const splitSummary = doc.splitTextToSize(summary, contentWidth);
        doc.text(splitSummary, margin, yPos);
        yPos += splitSummary.length * 5 + 10;

        // ============ CAREER INTERESTS & GOALS ============
        if (studentProfile?.interests?.length || studentProfile?.goals?.length) {
            doc.setTextColor(...primaryColor);
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('CAREER FOCUS', margin, yPos);
            yPos += 3;
            drawLine(yPos, primaryColor);
            yPos += 8;

            doc.setTextColor(...textDark);
            doc.setFontSize(10);

            if (studentProfile?.interests?.length) {
                doc.setFont('helvetica', 'bold');
                doc.text('Interests: ', margin, yPos);
                doc.setFont('helvetica', 'normal');
                const interestsText = studentProfile.interests.join(', ');
                doc.text(interestsText, margin + 20, yPos);
                yPos += 7;
            }

            if (studentProfile?.goals?.length) {
                doc.setFont('helvetica', 'bold');
                doc.text('Goals: ', margin, yPos);
                doc.setFont('helvetica', 'normal');
                const goalsText = studentProfile.goals.join(', ');
                doc.text(goalsText, margin + 14, yPos);
                yPos += 7;
            }

            yPos += 5;
        }

        // ============ CAREER PROGRESSION ROADMAP ============
        doc.setTextColor(...primaryColor);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('5-YEAR CAREER ROADMAP', margin, yPos);
        yPos += 3;
        drawLine(yPos, primaryColor);
        yPos += 10;

        if (roadmap && roadmap.length > 0) {
            roadmap.forEach((year, index) => {
                // Check if we need a new page
                if (yPos > 250) {
                    doc.addPage();
                    yPos = 20;
                }

                // Year badge
                doc.setFillColor(...primaryColor);
                doc.roundedRect(margin, yPos - 4, 20, 8, 2, 2, 'F');
                doc.setTextColor(255, 255, 255);
                doc.setFontSize(9);
                doc.setFont('helvetica', 'bold');
                doc.text(`Y${year.year}`, margin + 10, yPos + 1, { align: 'center' });

                // Role title
                doc.setTextColor(...textDark);
                doc.setFontSize(12);
                doc.setFont('helvetica', 'bold');
                doc.text(year.role || `Role Year ${year.year}`, margin + 25, yPos);
                yPos += 6;

                // Focus area
                doc.setTextColor(...textMuted);
                doc.setFontSize(9);
                doc.setFont('helvetica', 'italic');
                const focus = doc.splitTextToSize(year.focus || '', contentWidth - 25);
                doc.text(focus, margin + 25, yPos);
                yPos += focus.length * 4 + 3;

                // Skills
                if (year.skills_to_acquire && year.skills_to_acquire.length > 0) {
                    doc.setTextColor(...textDark);
                    doc.setFontSize(9);
                    doc.setFont('helvetica', 'normal');

                    year.skills_to_acquire.forEach(skill => {
                        doc.text(`• ${skill}`, margin + 25, yPos);
                        yPos += 4.5;
                    });
                }

                yPos += 8;
            });
        }

        // ============ SKILLS SUMMARY ============
        if (yPos > 220) {
            doc.addPage();
            yPos = 20;
        }

        doc.setTextColor(...primaryColor);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('KEY SKILLS TO DEVELOP', margin, yPos);
        yPos += 3;
        drawLine(yPos, primaryColor);
        yPos += 10;

        // Collect all unique skills
        const allSkills = roadmap?.flatMap(y => y.skills_to_acquire || []) || [];
        const uniqueSkills = [...new Set(allSkills)];

        if (uniqueSkills.length > 0) {
            doc.setTextColor(...textDark);
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');

            // Display skills in columns
            const skillsPerColumn = Math.ceil(uniqueSkills.length / 2);
            const col1 = uniqueSkills.slice(0, skillsPerColumn);
            const col2 = uniqueSkills.slice(skillsPerColumn);

            const startY = yPos;
            col1.forEach((skill, i) => {
                doc.text(`• ${skill}`, margin, startY + (i * 5));
            });

            col2.forEach((skill, i) => {
                doc.text(`• ${skill}`, margin + contentWidth / 2, startY + (i * 5));
            });

            yPos = startY + Math.max(col1.length, col2.length) * 5 + 10;
        }

        // ============ FOOTER ============
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setTextColor(...textMuted);
            doc.setFontSize(8);
            doc.text(
                `Generated by OPEC - AI Career Guidance Platform | Page ${i} of ${pageCount}`,
                pageWidth / 2,
                doc.internal.pageSize.getHeight() - 10,
                { align: 'center' }
            );
        }

        // Save the PDF
        const fileName = `${(studentProfile?.name || 'CareerPath').replace(/\s+/g, '_')}_Resume.pdf`;
        doc.save(fileName);

        setIsGenerating(false);
        setGeneratedSuccess(true);

        // Reset success state after 3 seconds
        setTimeout(() => setGeneratedSuccess(false), 3000);
    };

    return (
        <Card className="p-6">
            <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg">
                        <FileText className="w-6 h-6 text-white" />
                    </div>
                    <div>
                        <h3 className="text-xl font-bold text-slate-900">📄 Professional Resume</h3>
                        <p className="text-sm text-slate-600">AI-generated career roadmap resume</p>
                    </div>
                </div>

                <motion.div
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                >
                    <Button
                        onClick={generateProfessionalResume}
                        disabled={isGenerating}
                        className={`flex items-center gap-2 ${generatedSuccess
                                ? 'bg-green-600 hover:bg-green-700'
                                : 'bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700'
                            }`}
                    >
                        {isGenerating ? (
                            <>
                                <Sparkles className="w-4 h-4 animate-spin" />
                                Generating...
                            </>
                        ) : generatedSuccess ? (
                            <>
                                <FileCheck className="w-4 h-4" />
                                Downloaded!
                            </>
                        ) : (
                            <>
                                <Download className="w-4 h-4" />
                                Download PDF
                            </>
                        )}
                    </Button>
                </motion.div>
            </div>

            {/* Resume Preview */}
            <div className="mt-4 p-4 bg-slate-50 border border-slate-200 rounded-lg">
                <h4 className="text-sm font-semibold text-slate-700 mb-3">Resume Contents:</h4>
                <div className="grid grid-cols-2 gap-4 text-sm">
                    <div className="flex items-center gap-2">
                        <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                        <span className="text-slate-600">Professional Summary</span>
                    </div>
                    <div className="flex items-center gap-2">
                        <div className="w-2 h-2 bg-purple-500 rounded-full"></div>
                        <span className="text-slate-600">5-Year Career Roadmap</span>
                    </div>
                    <div className="flex items-center gap-2">
                        <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                        <span className="text-slate-600">Skills to Develop</span>
                    </div>
                    <div className="flex items-center gap-2">
                        <div className="w-2 h-2 bg-orange-500 rounded-full"></div>
                        <span className="text-slate-600">Career Focus & Goals</span>
                    </div>
                </div>
            </div>

            <p className="mt-4 text-xs text-slate-500">
                💡 Your resume includes your personalized career roadmap, skill development plan, and professional summary based on your profile and AI analysis.
            </p>
        </Card>
    );
}
